<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Chapter 4 Linear Models | Steffi’s Practical Guide</title>
<meta name="author" content="Steffi LaZerte">
<meta name="description" content="4.1 Preamble library(tidyverse) library(palmerpenguins) library(patchwork) # putting figures together library(car) # For Anova() and vif() functions Here we’re talking about linear relationships....">
<meta name="generator" content="bookdown 0.22.11 with bs4_book()">
<meta property="og:title" content="Chapter 4 Linear Models | Steffi’s Practical Guide">
<meta property="og:type" content="book">
<meta property="og:description" content="4.1 Preamble library(tidyverse) library(palmerpenguins) library(patchwork) # putting figures together library(car) # For Anova() and vif() functions Here we’re talking about linear relationships....">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="Chapter 4 Linear Models | Steffi’s Practical Guide">
<meta name="twitter:description" content="4.1 Preamble library(tidyverse) library(palmerpenguins) library(patchwork) # putting figures together library(car) # For Anova() and vif() functions Here we’re talking about linear relationships....">
<!-- JS --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/6.4.6/fuse.js" integrity="sha512-zv6Ywkjyktsohkbp9bb45V6tEMoWhzFzXis+LrMehmJZZSys19Yxf1dopHx7WzIKxr5tK2dVcYmaCk2uqdjF4A==" crossorigin="anonymous"></script><script src="https://kit.fontawesome.com/6ecbd6c532.js" crossorigin="anonymous"></script><script src="libs/header-attrs-2.9/header-attrs.js"></script><script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="libs/bootstrap-4.6.0/bootstrap.min.css" rel="stylesheet">
<script src="libs/bootstrap-4.6.0/bootstrap.bundle.min.js"></script><script src="libs/bs3compat-0.3.0/transition.js"></script><script src="libs/bs3compat-0.3.0/tabs.js"></script><script src="libs/bs3compat-0.3.0/bs3compat.js"></script><link href="libs/bs4_book-1.0.0/bs4_book.css" rel="stylesheet">
<script src="libs/bs4_book-1.0.0/bs4_book.js"></script><script src="libs/htmlwidgets-1.5.4/htmlwidgets.js"></script><script src="libs/d3-bundle-5.16.0/d3-bundle.min.js"></script><script src="libs/d3-lasso-0.0.5/d3-lasso.min.js"></script><script src="libs/save-svg-as-png-1.4.17/save-svg-as-png.min.js"></script><link href="libs/ggiraphjs-0.4.1/ggiraphjs.min.css" rel="stylesheet">
<script src="libs/ggiraphjs-0.4.1/ggiraphjs.min.js"></script><script src="libs/girafe-binding-0.7.10/girafe.js"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/autocomplete.js/0.38.0/autocomplete.jquery.min.js" integrity="sha512-GU9ayf+66Xx2TmpxqJpliWbT5PiGYxpaG8rfnBEk1LL8l1KGkRShhngwdXK1UgqhAzWpZHSiYPc09/NwDQIGyg==" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/mark.min.js" integrity="sha512-5CYOlHXGh6QpOFA/TeTylKLWfB3ftPsde7AnmhuitiTX4K5SqCLBeKro6sPS8ilsz1Q4NRx3v8Ko2IBiszzdww==" crossorigin="anonymous"></script><!-- CSS --><link rel="stylesheet" href="style.css">
</head>
<body data-spy="scroll" data-target="#toc">

<div class="container-fluid">
<div class="row">
  <header class="col-sm-12 col-lg-3 sidebar sidebar-book"><a class="sr-only sr-only-focusable" href="#content">Skip to main content</a>

    <div class="d-flex align-items-start justify-content-between">
      <h1>
        <a href="index.html" title="">Steffi’s Practical Guide</a>
      </h1>
      <button class="btn btn-outline-primary d-lg-none ml-2 mt-1" type="button" data-toggle="collapse" data-target="#main-nav" aria-expanded="true" aria-controls="main-nav"><i class="fas fa-bars"></i><span class="sr-only">Show table of contents</span></button>
    </div>

    <div id="main-nav" class="collapse-lg">
      <form role="search">
        <input id="search" class="form-control" type="search" placeholder="Search" aria-label="Search">
</form>

      <nav aria-label="Table of contents"><h2>Table of contents</h2>
        <ul class="book-toc list-unstyled">
<li><a class="" href="index.html"><span class="header-section-number">1</span> Introduction</a></li>
<li><a class="" href="workflow.html"><span class="header-section-number">2</span> Workflow</a></li>
<li><a class="" href="data-exploration.html"><span class="header-section-number">3</span> Data Exploration</a></li>
<li><a class="active" href="linear-models.html"><span class="header-section-number">4</span> Linear Models</a></li>
<li><a class="" href="appendix-model-diagnostics.html">Appendix Model Diagnostics</a></li>
<li><a class="" href="appendix-further-reading.html">Appendix Further Reading</a></li>
</ul>

        <div class="book-extra">
          
        </div>
      </nav>
</div>
  </header><main class="col-sm-12 col-md-9 col-lg-7" id="content"><div id="linear-models" class="section level1" number="4">
<h1>
<span class="header-section-number">4</span> Linear Models<a class="anchor" aria-label="anchor" href="#linear-models"><i class="fas fa-link"></i></a>
</h1>
<div id="preamble" class="section level2" number="4.1">
<h2>
<span class="header-section-number">4.1</span> Preamble<a class="anchor" aria-label="anchor" href="#preamble"><i class="fas fa-link"></i></a>
</h2>
<div class="sourceCode" id="cb4"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyverse.tidyverse.org">tidyverse</a></span><span class="op">)</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://allisonhorst.github.io/palmerpenguins/">palmerpenguins</a></span><span class="op">)</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://patchwork.data-imaginist.com">patchwork</a></span><span class="op">)</span> <span class="co"># putting figures together</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://r-forge.r-project.org/projects/car/">car</a></span><span class="op">)</span> <span class="co"># For Anova() and vif() functions</span></code></pre></div>
<p>Here we’re talking about <em>linear</em> relationships. There are plenty of other types of models (e.g., exponential) which deal with non-linear relationships or a mix of linear and non-linear (e.g., GAMs).</p>
<blockquote>
<p><strong>Disclaimer:</strong></p>
<p>The models included here are examples, they’re not the best (or most sensible) questions to ask, and often explore correlated features rather than features that we might actually assume causation.</p>
<p>Technically these might be better explored using Standardised Major Axis Estimate (SMA) in the smatr package. But for now, the’ll suffice 😁</p>
</blockquote>
</div>
<div id="general-workflow" class="section level2" number="4.2">
<h2>
<span class="header-section-number">4.2</span> General Workflow<a class="anchor" aria-label="anchor" href="#general-workflow"><i class="fas fa-link"></i></a>
</h2>
<ol style="list-style-type: decimal">
<li>Decide on your question(s)</li>
<li>Preliminary data exploration</li>
<li>Decide on a model (linear model, generalized linear model, mixed model, etc.)</li>
<li>Run model</li>
<li>Check model diagnostics</li>
<li>Interpret model</li>
</ol>
</div>
<div id="simple-lms-in-r" class="section level2" number="4.3">
<h2>
<span class="header-section-number">4.3</span> (Simple) LMs in R<a class="anchor" aria-label="anchor" href="#simple-lms-in-r"><i class="fas fa-link"></i></a>
</h2>
<div id="requirements" class="section level3 unnumbered">
<h3>Requirements<a class="anchor" aria-label="anchor" href="#requirements"><i class="fas fa-link"></i></a>
</h3>
<ul>
<li>
<strong>Continuous response</strong> (<code>y</code>)
<ul>
<li>no count data, no binary (binomial) data, no proprotions (although could be transformed)</li>
</ul>
</li>
<li>
<strong>Continuous or categorical predictors</strong> (<code>x1</code>, <code>x2</code>, etc.)</li>
</ul>
</div>
<div id="assumptions" class="section level3 unnumbered">
<h3>Assumptions<a class="anchor" aria-label="anchor" href="#assumptions"><i class="fas fa-link"></i></a>
</h3>
<ul>
<li>
<strong>Linear relationship</strong> between <code>y</code> and <code>x</code>s.</li>
<li>
<strong>Independence</strong> - Observations are independent (i.e. residuals are independent)
<ul>
<li>no hierarchical sampling, no nested designs, variables are based on each other</li>
</ul>
</li>
<li>
<strong>Normality</strong> - Residuals are normally distributed</li>
<li>
<strong>Constant variance</strong> - There is constant variance in residuals (no heteroscedasticity)</li>
</ul>
</div>
<div id="cautions" class="section level3 unnumbered">
<h3>Cautions<a class="anchor" aria-label="anchor" href="#cautions"><i class="fas fa-link"></i></a>
</h3>
<ul>
<li><strong>Multicollinearity</strong></li>
<li><strong>Influence</strong></li>
</ul>
<blockquote>
<p>See <a href="appendix-model-diagnostics.html">Diagnostics</a> section for more details</p>
</blockquote>
</div>
<div id="types-of-models" class="section level3 unnumbered">
<h3>Types of models<a class="anchor" aria-label="anchor" href="#types-of-models"><i class="fas fa-link"></i></a>
</h3>
<ul>
<li>
<strong>Regression</strong> - Continuous predictor (<code>x</code>)</li>
<li>
<strong>Multiple regression</strong> - More than one continuous predictor
(<code>x1</code>, <code>x2</code>, …)</li>
<li>
<strong>ANOVA</strong> - Categorical predictor(s) (<code>x1</code>, <code>x2</code>, …)</li>
<li>
<strong>ANCOVA</strong> - Mix of categorical and continuous predictors (<code>x1</code>, <code>x2</code>, …)</li>
</ul>
</div>
<div id="run-models-with-lm" class="section level3 unnumbered">
<h3>Run models with <code>lm()</code><a class="anchor" aria-label="anchor" href="#run-models-with-lm"><i class="fas fa-link"></i></a>
</h3>
<div class="align-centre large">
<p><code><a href="https://rdrr.io/r/stats/lm.html">lm(y ~ x1 + x2, data = data)</a></code></p>
</div>
<blockquote>
<p>R will figure out the underlying model type (regression, ANOVA, ANCOVA etc.)</p>
</blockquote>
<p>Store your model as an object, here <code>m</code></p>
<div class="sourceCode" id="cb5"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">m</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">body_mass_g</span> <span class="op">~</span> <span class="va">bill_depth_mm</span>, data <span class="op">=</span> <span class="va">penguins</span><span class="op">)</span></code></pre></div>
<p><code>m</code> is a model object</p>
<div class="sourceCode" id="cb6"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/class.html">class</a></span><span class="op">(</span><span class="va">m</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] "lm"</code></pre>
<p>This contains all the information about the model</p>
<p>Use <code><a href="https://rdrr.io/r/base/summary.html">summary()</a></code> to show summary table:</p>
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">m</span><span class="op">)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = body_mass_g ~ bill_depth_mm, data = penguins)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -1607.38  -510.10   -66.96   462.43  1819.28 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)    7488.65     335.22   22.34   &lt;2e-16 ***
## bill_depth_mm  -191.64      19.42   -9.87   &lt;2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 708.1 on 340 degrees of freedom
##   (2 observations deleted due to missingness)
## Multiple R-squared:  0.2227, Adjusted R-squared:  0.2204 
## F-statistic: 97.41 on 1 and 340 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Use <code><a href="https://rdrr.io/r/stats/anova.html">anova()</a></code> to show Anova table (Type I), or, better, <code><a href="https://rdrr.io/pkg/car/man/Anova.html">Anova()</a></code> (from the car package) to use type II or III:</p>
<div class="sourceCode" id="cb10"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/pkg/car/man/Anova.html">Anova</a></span><span class="op">(</span><span class="va">m</span>, type <span class="op">=</span> <span class="st">"III"</span><span class="op">)</span></code></pre></div>
<pre><code>## Anova Table (Type III tests)
## 
## Response: body_mass_g
##                  Sum Sq  Df F value    Pr(&gt;F)    
## (Intercept)   250215572   1 499.060 &lt; 2.2e-16 ***
## bill_depth_mm  48840779   1  97.414 &lt; 2.2e-16 ***
## Residuals     170466918 340                      
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div id="summary-tables-vs.-anova-tables" class="section level3 unnumbered">
<h3>Summary tables vs. ANOVA tables<a class="anchor" aria-label="anchor" href="#summary-tables-vs.-anova-tables"><i class="fas fa-link"></i></a>
</h3>
<blockquote>
<p><strong>NOTE</strong><br>
Even though traditionally a summary table is used to evaluate a regression and
an ANOVA table is used to evaluate an ANOVA or an ANCOVA, they can both be used
to assess any linear model, they just ask slightly different questions</p>
</blockquote>
<p><strong>Summary tables</strong></p>
<p>Summary tables show the results of very specific statistical questions.
The precise interpretation of these results depends on whether the parameters
are continuous, categorical, or a mix, and whether there are interactions or not.
(see specific sections for interpretations).</p>
<p><strong>ANOVA tables</strong></p>
<p>Broadly, an ANOVA table asks whether there is an <strong>overall</strong> effect of any
parameter, but it <strong>does not</strong> specify what that effect is.</p>
<p>This means that for <em>continuous</em> parameters you don’t know if the effect is
positive or negative.</p>
<p>For <em>categorical</em> parameters you don’t know which category has what effect
(but see Post-Hoc analyses which can be used to tease this apart).</p>
</div>
</div>
<div id="regressions" class="section level2" number="4.4">
<h2>
<span class="header-section-number">4.4</span> Regressions<a class="anchor" aria-label="anchor" href="#regressions"><i class="fas fa-link"></i></a>
</h2>
<ul>
<li>Continuous response (<code>y</code>) and <strong>continuous</strong> predictor(s) (<code>x</code>)</li>
<li>What might we be interested in?</li>
</ul>
<p><img src="steffis-practical-guide_files/figure-html/unnamed-chunk-11-1.png" width="90%" style="display: block; margin: auto;"><img src="steffis-practical-guide_files/figure-html/unnamed-chunk-11-2.png" width="90%" style="display: block; margin: auto;"></p>
<div id="create-model" class="section level3 unnumbered">
<h3>Create Model<a class="anchor" aria-label="anchor" href="#create-model"><i class="fas fa-link"></i></a>
</h3>
<p>To see if these relationships are significant we run/create a linear model…</p>
<div class="sourceCode" id="cb12"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">m</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">body_mass_g</span> <span class="op">~</span> <span class="va">flipper_length_mm</span> <span class="op">+</span> <span class="va">bill_length_mm</span>, data <span class="op">=</span> <span class="va">penguins</span><span class="op">)</span></code></pre></div>
<blockquote>
<p><strong>Wait!</strong> We shouldn’t interpret until we’ve checked our diagnostics</p>
</blockquote>
</div>
<div id="model-diagnostics" class="section level3 unnumbered">
<h3>Model Diagnostics<a class="anchor" aria-label="anchor" href="#model-diagnostics"><i class="fas fa-link"></i></a>
</h3>
<ul>
<li>Checking Assumptions
<ul>
<li>Normality (of residuals)</li>
<li>Constant Variance (no heteroscedasticity)</li>
</ul>
</li>
<li>Other cautions
<ul>
<li>Influential observations (Cook’s D)</li>
<li>Multiple collinearity (with more than one <code>x</code> or explanatory variables)</li>
</ul>
</li>
</ul>
<blockquote>
<p>See <a href="appendix-model-diagnostics.html">Diagnostics</a> section for more details</p>
</blockquote>
<div class="sourceCode" id="cb13"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">d</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span>residuals <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/residuals.html">residuals</a></span><span class="op">(</span><span class="va">m</span><span class="op">)</span>,    
                std_residuals <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/influence.measures.html">rstudent</a></span><span class="op">(</span><span class="va">m</span><span class="op">)</span>, 
                fitted <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/fitted.values.html">fitted</a></span><span class="op">(</span><span class="va">m</span><span class="op">)</span>,          
                cooks <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/influence.measures.html">cooks.distance</a></span><span class="op">(</span><span class="va">m</span><span class="op">)</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu">mutate</span><span class="op">(</span>obs <span class="op">=</span> <span class="fl">1</span><span class="op">:</span><span class="fu">n</span><span class="op">(</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<div id="normality-and-heteroscedasticity" class="section level4 unnumbered">
<h4>Normality and Heteroscedasticity<a class="anchor" aria-label="anchor" href="#normality-and-heteroscedasticity"><i class="fas fa-link"></i></a>
</h4>
<div class="sourceCode" id="cb14"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">g1</span> <span class="op">&lt;-</span> <span class="fu">ggplot</span><span class="op">(</span>data <span class="op">=</span> <span class="va">d</span>, <span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">std_residuals</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">geom_histogram</span><span class="op">(</span>bins <span class="op">=</span> <span class="fl">20</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">ggtitle</span><span class="op">(</span><span class="st">"Histogram of residuals"</span><span class="op">)</span>

<span class="va">g2</span> <span class="op">&lt;-</span> <span class="fu">ggplot</span><span class="op">(</span>data <span class="op">=</span> <span class="va">d</span>, <span class="fu">aes</span><span class="op">(</span>sample <span class="op">=</span> <span class="va">std_residuals</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">stat_qq</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">stat_qq_line</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">ggtitle</span><span class="op">(</span><span class="st">"QQ Normality plot of residuals"</span><span class="op">)</span>

<span class="va">g3</span> <span class="op">&lt;-</span> <span class="fu">ggplot</span><span class="op">(</span><span class="va">d</span>, <span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">fitted</span>, y <span class="op">=</span> <span class="va">std_residuals</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">geom_point</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">geom_hline</span><span class="op">(</span>yintercept <span class="op">=</span> <span class="fl">0</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">ggtitle</span><span class="op">(</span><span class="st">"Heteroscedacity: Residuals vs. fitted"</span><span class="op">)</span>

<span class="op">(</span><span class="va">g1</span> <span class="op">+</span> <span class="va">g2</span><span class="op">)</span> <span class="op">/</span> <span class="va">g3</span></code></pre></div>
<div class="inline-figure"><img src="steffis-practical-guide_files/figure-html/unnamed-chunk-14-1.png" width="90%" style="display: block; margin: auto;"></div>
</div>
<div id="influence" class="section level4 unnumbered">
<h4>Influence<a class="anchor" aria-label="anchor" href="#influence"><i class="fas fa-link"></i></a>
</h4>
<p><strong>Cook’s D</strong></p>
<div class="sourceCode" id="cb15"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu">ggplot</span><span class="op">(</span><span class="va">d</span>, <span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">obs</span>, y <span class="op">=</span> <span class="va">cooks</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">geom_point</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">geom_hline</span><span class="op">(</span>yintercept <span class="op">=</span> <span class="fl">1</span>, linetype <span class="op">=</span> <span class="st">"dotted"</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">geom_hline</span><span class="op">(</span>yintercept <span class="op">=</span> <span class="fl">4</span><span class="op">/</span><span class="fu"><a href="https://rdrr.io/r/base/nrow.html">nrow</a></span><span class="op">(</span><span class="va">penguins</span><span class="op">)</span>, 
             linetype <span class="op">=</span> <span class="st">"dashed"</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">ggtitle</span><span class="op">(</span><span class="st">"Cook's D: Influential observations"</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="steffis-practical-guide_files/figure-html/unnamed-chunk-15-1.png" width="90%" style="display: block; margin: auto;"></div>
<blockquote>
<p>Pretty good!</p>
</blockquote>
</div>
<div id="multicollinearity-collinearity" class="section level4 unnumbered">
<h4>Multicollinearity (collinearity)<a class="anchor" aria-label="anchor" href="#multicollinearity-collinearity"><i class="fas fa-link"></i></a>
</h4>
<p>Look at our two explanatory variables</p>
<div class="sourceCode" id="cb16"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu">ggplot</span><span class="op">(</span>data <span class="op">=</span> <span class="va">penguins</span>, <span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">flipper_length_mm</span>, y <span class="op">=</span> <span class="va">bill_length_mm</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">geom_point</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">stat_smooth</span><span class="op">(</span>method <span class="op">=</span> <span class="st">"lm"</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="steffis-practical-guide_files/figure-html/unnamed-chunk-16-1.png" width="90%" style="display: block; margin: auto;"></div>
<blockquote>
<p>Definitely correlated.
We need to investigate if it interferes with the model.</p>
</blockquote>
<p>Use <code><a href="https://rdrr.io/pkg/car/man/vif.html">vif()</a></code> function from <code>car</code> package<a class="footnote-ref" tabindex="0" data-toggle="popover" data-content="&lt;p&gt;vif = variance inflation factor; Can be interpreted as how much influence the variable has on the model&lt;/p&gt;"><sup>1</sup></a></p>
<div class="sourceCode" id="cb17"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://r-forge.r-project.org/projects/car/">car</a></span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/pkg/car/man/vif.html">vif</a></span><span class="op">(</span><span class="va">m</span><span class="op">)</span></code></pre></div>
<pre><code>## flipper_length_mm    bill_length_mm 
##          1.756154          1.756154</code></pre>
<blockquote>
<p>Hmm, that’s pretty good (looking for &lt; 10).</p>
<p>So we can assume that the correlation is not a problem for how we interpret the model</p>
</blockquote>
</div>
</div>
<div id="summary-tables" class="section level3 unnumbered">
<h3>Summary Tables<a class="anchor" aria-label="anchor" href="#summary-tables"><i class="fas fa-link"></i></a>
</h3>
<div class="sourceCode" id="cb19"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">m</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">body_mass_g</span> <span class="op">~</span> <span class="va">flipper_length_mm</span> <span class="op">+</span> <span class="va">bill_length_mm</span>, data <span class="op">=</span> <span class="va">penguins</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">m</span><span class="op">)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = body_mass_g ~ flipper_length_mm + bill_length_mm, 
##     data = penguins)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -1090.5  -285.7   -32.1   244.2  1287.5 
## 
## Coefficients:
##                    Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)       -5736.897    307.959 -18.629   &lt;2e-16 ***
## flipper_length_mm    48.145      2.011  23.939   &lt;2e-16 ***
## bill_length_mm        6.047      5.180   1.168    0.244    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 394.1 on 339 degrees of freedom
##   (2 observations deleted due to missingness)
## Multiple R-squared:   0.76,  Adjusted R-squared:  0.7585 
## F-statistic: 536.6 on 2 and 339 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>That’s a lot of information! Let’s break it down.</p>
<p><strong>Model</strong></p>
<pre><code>## Call:
## lm(formula = body_mass_g ~ flipper_length_mm + bill_length_mm, 
##     data = penguins)</code></pre>
<p><strong>Missing observations</strong></p>
<pre><code>##   (2 observations deleted due to missingness)</code></pre>
<p><strong>R<sup>2</sup> and adjusted R<sup>2</sup></strong></p>
<ul>
<li>Adjusted for the number of parameters</li>
</ul>
<pre><code>## Multiple R-squared:   0.76,  Adjusted R-squared:  0.7585 </code></pre>
<p><strong>Effects</strong></p>
<pre><code>##                    Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)       -5736.897    307.959 -18.629   &lt;2e-16 ***
## flipper_length_mm    48.145      2.011  23.939   &lt;2e-16 ***
## bill_length_mm        6.047      5.180   1.168    0.244    </code></pre>
<div class="inline-table"><table class="table table-sm">
<thead><tr>
<th style="text-align:left;">
Column
</th>
<th style="text-align:left;">
Description
</th>
</tr></thead>
<tbody>
<tr>
<td style="text-align:left;">
<code>Estimate</code>
</td>
<td style="text-align:left;">
Intercept/Slope of the effect
</td>
</tr>
<tr>
<td style="text-align:left;">
<code>Std. Error</code>
</td>
<td style="text-align:left;">
Variability in the estimates
</td>
</tr>
<tr>
<td style="text-align:left;">
<code>t value</code>
</td>
<td style="text-align:left;">
Test statistic<a class="footnote-ref" tabindex="0" data-toggle="popover" data-content="&lt;p&gt;Think of it as a holistic combination of estimate and variability&lt;/p&gt;"><sup>2</sup></a>
</td>
</tr>
<tr>
<td style="text-align:left;">
<code>Pr(&gt;|t|)</code>
</td>
<td style="text-align:left;">
<strong>P-value</strong>, significance of the results<a class="footnote-ref" tabindex="0" data-toggle="popover" data-content="&lt;p&gt;Probability of getting &lt;code&gt;t-value&lt;/code&gt; by chance&lt;/p&gt;"><sup>3</sup></a>
</td>
</tr>
</tbody>
</table></div>
</div>
<div id="interpreting-effects" class="section level3 unnumbered">
<h3>Interpreting effects<a class="anchor" aria-label="anchor" href="#interpreting-effects"><i class="fas fa-link"></i></a>
</h3>
<pre><code>##                    Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)       -5736.897    307.959 -18.629   &lt;2e-16 ***
## flipper_length_mm    48.145      2.011  23.939   &lt;2e-16 ***
## bill_length_mm        6.047      5.180   1.168    0.244    </code></pre>
<ul>
<li>
<strong>Intercept</strong>
<ul>
<li>Significant (P = &lt; 2.2e-16)</li>
<li>Penguins with a flipper length of 0 mm and a bill length of 0 mm are predicted to have a body mass of -5736.9 g</li>
</ul>
</li>
<li>
<strong>Flipper Length</strong>
<ul>
<li>Significant (P = &lt; 2.2e-16)</li>
<li>For each 1 mm increase in flipper length, body mass is predicted to increase by 48.14 g</li>
</ul>
</li>
<li>
<strong>Bill Length</strong>
<ul>
<li>Non-significant (P = 0.244)</li>
<li>So we don’t interpret)</li>
</ul>
</li>
</ul>
<p>(<strong>Note</strong>: 2e<sup>-16</sup> = 0.0000000000000002, R uses this as the smallest number)</p>
<blockquote>
<p><strong>Therefore</strong></p>
<p>There is a significant relationship between flipper length and body mass.<br>
But <em>not</em> between bill length and body mass (when including and controlling for
flipper length)</p>
</blockquote>
</div>
<div id="interpreting-the-effects-as-a-model" class="section level3 unnumbered">
<h3>Interpreting the effects as a model<a class="anchor" aria-label="anchor" href="#interpreting-the-effects-as-a-model"><i class="fas fa-link"></i></a>
</h3>
<p>First we have the general equation for a line<a class="footnote-ref" tabindex="0" data-toggle="popover" data-content="&lt;p&gt;(remember highschool?)&lt;/p&gt;"><sup>4</sup></a>.</p>
<p><span class="math inline">\(y = mx + b\)</span></p>
<ul>
<li>
<span class="math inline">\(m\)</span> = slope of <span class="math inline">\(x\)</span>
</li>
<li>
<span class="math inline">\(b\)</span> = intercept</li>
</ul>
<p>For two explanatory variables</p>
<p><span class="math inline">\(y = m_1x_1 + m_2x_2 + b\)</span></p>
<p>For our specific model</p>
<p><span class="math inline">\(y = 48.14x_1 + 6.05x_2 + (-5736.9)\)</span></p>
</div>
<div id="extra" class="section level3 unnumbered">
<h3>Extra<a class="anchor" aria-label="anchor" href="#extra"><i class="fas fa-link"></i></a>
</h3>
<blockquote>
<p>Why no effect of Bill Length? {-}</p>
</blockquote>
<div class="inline-figure"><img src="steffis-practical-guide_files/figure-html/unnamed-chunk-26-1.png" width="100%" style="display: block; margin: auto;"></div>
<div class="sourceCode" id="cb26"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">m</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">body_mass_g</span> <span class="op">~</span> <span class="va">bill_length_mm</span>, data <span class="op">=</span> <span class="va">penguins</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">m</span><span class="op">)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = body_mass_g ~ bill_length_mm, data = penguins)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -1762.08  -446.98    32.59   462.31  1636.86 
## 
## Coefficients:
##                Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)     362.307    283.345   1.279    0.202    
## bill_length_mm   87.415      6.402  13.654   &lt;2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 645.4 on 340 degrees of freedom
##   (2 observations deleted due to missingness)
## Multiple R-squared:  0.3542, Adjusted R-squared:  0.3523 
## F-statistic: 186.4 on 1 and 340 DF,  p-value: &lt; 2.2e-16</code></pre>
<ul>
<li>Our hypothesis is of <em>causation</em> but really, this is just correlation</li>
<li>Flipper length is the ‘better’ predictor of body mass</li>
<li>When flipper length in the model, no extra variation explained by bill length</li>
<li>When flipper length <em>not</em> in the model, some variation left to be explained</li>
</ul>
<div class="sourceCode" id="cb28"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">m</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">body_mass_g</span> <span class="op">~</span> <span class="va">bill_length_mm</span>, data <span class="op">=</span> <span class="va">penguins</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">m</span><span class="op">)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = body_mass_g ~ bill_length_mm, data = penguins)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -1762.08  -446.98    32.59   462.31  1636.86 
## 
## Coefficients:
##                Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)     362.307    283.345   1.279    0.202    
## bill_length_mm   87.415      6.402  13.654   &lt;2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 645.4 on 340 degrees of freedom
##   (2 observations deleted due to missingness)
## Multiple R-squared:  0.3542, Adjusted R-squared:  0.3523 
## F-statistic: 186.4 on 1 and 340 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<div id="anovas" class="section level2" number="4.5">
<h2>
<span class="header-section-number">4.5</span> ANOVAs<a class="anchor" aria-label="anchor" href="#anovas"><i class="fas fa-link"></i></a>
</h2>
<ul>
<li>Continuous response (<code>y</code>) and categorical predictor(s) (<code>x</code>)</li>
<li>What might we be interested in?</li>
</ul>
<p><img src="steffis-practical-guide_files/figure-html/unnamed-chunk-29-1.png" width="90%" style="display: block; margin: auto;"><img src="steffis-practical-guide_files/figure-html/unnamed-chunk-29-2.png" width="90%" style="display: block; margin: auto;"></p>
<div id="create-model-1" class="section level3 unnumbered">
<h3>Create Model<a class="anchor" aria-label="anchor" href="#create-model-1"><i class="fas fa-link"></i></a>
</h3>
<p>To see if these relationships are significant we run/create a linear model…</p>
<div class="sourceCode" id="cb30"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">m</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">body_mass_g</span> <span class="op">~</span> <span class="va">species</span> <span class="op">+</span> <span class="va">sex</span>, data <span class="op">=</span> <span class="va">penguins</span><span class="op">)</span></code></pre></div>
<blockquote>
<p>But first diagnostics…</p>
</blockquote>
</div>
<div id="model-diagnostics-1" class="section level3 unnumbered">
<h3>Model Diagnostics<a class="anchor" aria-label="anchor" href="#model-diagnostics-1"><i class="fas fa-link"></i></a>
</h3>
<blockquote>
<p>As with regressions…</p>
</blockquote>
<ul>
<li>Checking Assumptions
<ul>
<li>Normality (of residuals)</li>
<li>Constant Variance (no heteroscedasticity)</li>
</ul>
</li>
<li>Other cautions
<ul>
<li>Influential observations (Cook’s D)</li>
<li>Multiple collinearity (with more than one <code>x</code> or explanatory variables)</li>
</ul>
</li>
</ul>
<blockquote>
<p>See <a href="appendix-model-diagnostics.html">Diagnostics</a> section for more details</p>
</blockquote>
<div class="sourceCode" id="cb31"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">d</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span>residuals <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/residuals.html">residuals</a></span><span class="op">(</span><span class="va">m</span><span class="op">)</span>,    
                std_residuals <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/influence.measures.html">rstudent</a></span><span class="op">(</span><span class="va">m</span><span class="op">)</span>, 
                fitted <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/fitted.values.html">fitted</a></span><span class="op">(</span><span class="va">m</span><span class="op">)</span>,          
                cooks <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/influence.measures.html">cooks.distance</a></span><span class="op">(</span><span class="va">m</span><span class="op">)</span><span class="op">)</span>   

<span class="va">d</span> <span class="op">&lt;-</span> <span class="fu">mutate</span><span class="op">(</span><span class="va">d</span>, obs <span class="op">=</span> <span class="fl">1</span><span class="op">:</span><span class="fu">n</span><span class="op">(</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<div class="sourceCode" id="cb32"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">d</span><span class="op">)</span></code></pre></div>
<pre><code>##    residuals std_residuals   fitted        cooks obs
## 1 -289.94196    -0.9201062 4039.942 0.0021071103   1
## 2  427.61319     1.3590567 3372.387 0.0045831843   2
## 3 -122.38681    -0.3879729 3372.387 0.0003754346   3
## 5   77.61319     0.2460043 3372.387 0.0001509858   4
## 6 -389.94196    -1.2387413 4039.942 0.0038112292   5
## 7  252.61319     0.8013974 3372.387 0.0015994740   6</code></pre>
<div id="normality-and-heteroscedasticity-1" class="section level4 unnumbered">
<h4>Normality and Heteroscedasticity<a class="anchor" aria-label="anchor" href="#normality-and-heteroscedasticity-1"><i class="fas fa-link"></i></a>
</h4>
<div class="sourceCode" id="cb34"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">g1</span> <span class="op">&lt;-</span> <span class="fu">ggplot</span><span class="op">(</span>data <span class="op">=</span> <span class="va">d</span>, <span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">std_residuals</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">geom_histogram</span><span class="op">(</span>bins <span class="op">=</span> <span class="fl">20</span><span class="op">)</span>

<span class="va">g2</span> <span class="op">&lt;-</span> <span class="fu">ggplot</span><span class="op">(</span>data <span class="op">=</span> <span class="va">d</span>, <span class="fu">aes</span><span class="op">(</span>sample <span class="op">=</span> <span class="va">std_residuals</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">stat_qq</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">stat_qq_line</span><span class="op">(</span><span class="op">)</span>

<span class="va">g3</span> <span class="op">&lt;-</span> <span class="fu">ggplot</span><span class="op">(</span><span class="va">d</span>, <span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">fitted</span>, y <span class="op">=</span> <span class="va">std_residuals</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">geom_point</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">geom_hline</span><span class="op">(</span>yintercept <span class="op">=</span> <span class="fl">0</span><span class="op">)</span>

<span class="op">(</span><span class="va">g1</span> <span class="op">+</span> <span class="va">g2</span><span class="op">)</span> <span class="op">/</span> <span class="va">g3</span></code></pre></div>
<div class="inline-figure"><img src="steffis-practical-guide_files/figure-html/unnamed-chunk-33-1.png" width="90%" style="display: block; margin: auto;"></div>
</div>
<div id="influence-1" class="section level4 unnumbered">
<h4>Influence<a class="anchor" aria-label="anchor" href="#influence-1"><i class="fas fa-link"></i></a>
</h4>
<p><strong>Cook’s D</strong></p>
<div class="sourceCode" id="cb35"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu">ggplot</span><span class="op">(</span><span class="va">d</span>, <span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">obs</span>, y <span class="op">=</span> <span class="va">cooks</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">geom_point</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">geom_hline</span><span class="op">(</span>yintercept <span class="op">=</span> <span class="fl">1</span>, linetype <span class="op">=</span> <span class="st">"dotted"</span><span class="op">)</span> <span class="op">+</span> <span class="co">#&lt;&lt;</span>
  <span class="fu">geom_hline</span><span class="op">(</span>yintercept <span class="op">=</span> <span class="fl">4</span><span class="op">/</span><span class="fu"><a href="https://rdrr.io/r/base/nrow.html">nrow</a></span><span class="op">(</span><span class="va">penguins</span><span class="op">)</span>, 
             linetype <span class="op">=</span> <span class="st">"dashed"</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="steffis-practical-guide_files/figure-html/unnamed-chunk-34-1.png" width="90%" style="display: block; margin: auto;"></div>
<blockquote>
<p>Overall not too bad</p>
</blockquote>
</div>
<div id="multicollinearity-collinearity-1" class="section level4 unnumbered">
<h4>Multicollinearity (collinearity)<a class="anchor" aria-label="anchor" href="#multicollinearity-collinearity-1"><i class="fas fa-link"></i></a>
</h4>
<ul>
<li>Only relevant with <strong>more than one explanatory variable</strong>
</li>
<li>Sometimes explanatory variables are so correlated they interfere with the model</li>
<li>Correlations between variables <em>might</em> be problematic (but not necessarily)</li>
</ul>
<p>Use <code><a href="https://rdrr.io/pkg/car/man/vif.html">vif()</a></code> function from <code>car</code> package<a class="footnote-ref" tabindex="0" data-toggle="popover" data-content="&lt;p&gt;vif = variance inflation factor; Can be interpreted as how much influence the variable has on the model&lt;/p&gt;"><sup>5</sup></a></p>
<div class="sourceCode" id="cb36"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://r-forge.r-project.org/projects/car/">car</a></span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/pkg/car/man/vif.html">vif</a></span><span class="op">(</span><span class="va">m</span><span class="op">)</span></code></pre></div>
<pre><code>##             GVIF Df GVIF^(1/(2*Df))
## species 1.000146  2        1.000036
## sex     1.000146  1        1.000073</code></pre>
<p>Here we consider the <code>GVIF^(1/2*Df))</code> value<sup>*</sup></p>
<p>Looks good!</p>
<p>(* See <code><a href="https://rdrr.io/pkg/car/man/vif.html">?vif</a></code> and the reference therein: Fox, J. and Monette, G. (1992) Generalized collinearity diagnostics. JASA, 87, 178–183.)</p>
</div>
</div>
<div id="summary-tables-1" class="section level3 unnumbered">
<h3>Summary Tables<a class="anchor" aria-label="anchor" href="#summary-tables-1"><i class="fas fa-link"></i></a>
</h3>
<div class="sourceCode" id="cb38"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">m</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">body_mass_g</span> <span class="op">~</span> <span class="va">species</span> <span class="op">+</span> <span class="va">sex</span>, data <span class="op">=</span> <span class="va">penguins</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">m</span><span class="op">)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = body_mass_g ~ species + sex, data = penguins)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -816.87 -217.80  -16.87  227.61  882.20 
## 
## Coefficients:
##                  Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)       3372.39      31.43 107.308   &lt;2e-16 ***
## speciesChinstrap    26.92      46.48   0.579    0.563    
## speciesGentoo     1377.86      39.10  35.236   &lt;2e-16 ***
## sexmale            667.56      34.70  19.236   &lt;2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 316.6 on 329 degrees of freedom
##   (11 observations deleted due to missingness)
## Multiple R-squared:  0.8468, Adjusted R-squared:  0.8454 
## F-statistic: 606.1 on 3 and 329 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>That’s a lot of information! Let’s break it down.</p>
<p><strong>Model</strong></p>
<pre><code>## Call:
## lm(formula = body_mass_g ~ species + sex, data = penguins)</code></pre>
<p><strong>Missing observations</strong></p>
<pre><code>##   (11 observations deleted due to missingness)</code></pre>
<p><strong>R<sup>2</sup> and adjusted R<sup>2</sup></strong></p>
<ul>
<li>Adjusted for the number of parameters</li>
</ul>
<pre><code>## Multiple R-squared:  0.8468, Adjusted R-squared:  0.8454 </code></pre>
<p><strong>Effects</strong></p>
<pre><code>##                  Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)       3372.39      31.43 107.308   &lt;2e-16 ***
## speciesChinstrap    26.92      46.48   0.579    0.563    
## speciesGentoo     1377.86      39.10  35.236   &lt;2e-16 ***
## sexmale            667.56      34.70  19.236   &lt;2e-16 ***</code></pre>
<div class="inline-table"><table class="table table-sm">
<thead><tr>
<th style="text-align:left;">
Column
</th>
<th style="text-align:left;">
Description
</th>
</tr></thead>
<tbody>
<tr>
<td style="text-align:left;">
<code>Estimate</code>
</td>
<td style="text-align:left;">
Intercept/Slope/Mean difference of the effect
</td>
</tr>
<tr>
<td style="text-align:left;">
<code>Std. Error</code>
</td>
<td style="text-align:left;">
Variability in the estimates
</td>
</tr>
<tr>
<td style="text-align:left;">
<code>t value</code>
</td>
<td style="text-align:left;">
Test statistic<a class="footnote-ref" tabindex="0" data-toggle="popover" data-content="&lt;p&gt;Think of it as a holistic combination of estimate and variability&lt;/p&gt;"><sup>6</sup></a>
</td>
</tr>
<tr>
<td style="text-align:left;">
<code>Pr(&gt;|t|)</code>
</td>
<td style="text-align:left;">
<strong>P-value</strong>, significance of the results<a class="footnote-ref" tabindex="0" data-toggle="popover" data-content="&lt;p&gt;Probability of getting &lt;code&gt;t-value&lt;/code&gt; by chance&lt;/p&gt;"><sup>7</sup></a>
</td>
</tr>
</tbody>
</table></div>
</div>
<div id="interpreting-effects-1" class="section level3 unnumbered">
<h3>Interpreting effects<a class="anchor" aria-label="anchor" href="#interpreting-effects-1"><i class="fas fa-link"></i></a>
</h3>
<pre><code>## (Intercept)       3372.39      31.43 107.308   &lt;2e-16 ***
## speciesChinstrap    26.92      46.48   0.579    0.563    
## speciesGentoo     1377.86      39.10  35.236   &lt;2e-16 ***
## sexmale            667.56      34.70  19.236   &lt;2e-16 ***</code></pre>
<ul>
<li>
<code>Estimate</code>
<ul>
<li>Treatment contrasts</li>
<li>Average <em>differences</em> among categories compared to the base category</li>
</ul>
</li>
<li>
<code>Std. Error</code>
<ul>
<li>Variability in the estimates</li>
</ul>
</li>
<li>
<code>t value</code>
<ul>
<li>Test statistic</li>
</ul>
</li>
<li>
<code>Pr(&gt;|t|)</code>
<ul>
<li>
<strong>P-value</strong>, significance of the <em>differences</em>
</li>
<li>Probability of getting <code>t-value</code> by chance</li>
</ul>
</li>
</ul>
<blockquote>
<p>Easier to interpret estimates if we consider a simpler model</p>
</blockquote>
<p><strong>A simpler model</strong></p>
<div class="sourceCode" id="cb45"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">m</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">body_mass_g</span> <span class="op">~</span> <span class="va">species</span>, data <span class="op">=</span> <span class="va">penguins</span><span class="op">)</span></code></pre></div>
<div class="sourceCode" id="cb46"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">m</span><span class="op">)</span></code></pre></div>
<pre><code>## (Intercept)       3700.66      37.62   98.37   &lt;2e-16 ***
## speciesChinstrap    32.43      67.51    0.48    0.631    
## speciesGentoo     1375.35      56.15   24.50   &lt;2e-16 ***</code></pre>
<p>Effect of <strong>Species</strong></p>
<ul>
<li>
<code>(Intercept)</code> represents base category (i.e. Adelie penguins)</li>
<li>Adelie have mean body mass of 3700.66 g</li>
<li>On average, Chinstrap penguins are 32.43 g heavier than Adelie penguins</li>
<li>On average, Gentoo penguins are 1375.35 g heavier than Adelie penguins</li>
</ul>
<blockquote>
<p>Back to original model</p>
</blockquote>
<div class="sourceCode" id="cb48"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">m</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">body_mass_g</span> <span class="op">~</span> <span class="va">species</span> <span class="op">+</span> <span class="va">sex</span>, data <span class="op">=</span> <span class="va">penguins</span><span class="op">)</span></code></pre></div>
<pre><code>## (Intercept)       3372.39      31.43 107.308   &lt;2e-16 ***
## speciesChinstrap    26.92      46.48   0.579    0.563    
## speciesGentoo     1377.86      39.10  35.236   &lt;2e-16 ***
## sexmale            667.56      34.70  19.236   &lt;2e-16 ***</code></pre>
<p>Effect of <strong>Species</strong> and <strong>Sex</strong></p>
<ul>
<li>
<code>(Intercept)</code> represents base category but is a combination of factors</li>
<li>Much more complicated to interpret</li>
<li>Comparisons are often not of interest anyway
(unless you’ve set up contrasts, which are advanced stats but awesome!)</li>
</ul>
<blockquote>
<p>So let’s look at ANOVA tables instead</p>
</blockquote>
</div>
<div id="anova-tables" class="section level3 unnumbered">
<h3>ANOVA Tables<a class="anchor" aria-label="anchor" href="#anova-tables"><i class="fas fa-link"></i></a>
</h3>
<div id="type-i" class="section level4" number="4.5.0.1">
<h4>
<span class="header-section-number">4.5.0.1</span> Type I<a class="anchor" aria-label="anchor" href="#type-i"><i class="fas fa-link"></i></a>
</h4>
<div class="sourceCode" id="cb50"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/stats/anova.html">anova</a></span><span class="op">(</span><span class="va">m</span><span class="op">)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Response: body_mass_g
##            Df    Sum Sq  Mean Sq F value    Pr(&gt;F)    
## species     2 145190219 72595110  724.21 &lt; 2.2e-16 ***
## sex         1  37090262 37090262  370.01 &lt; 2.2e-16 ***
## Residuals 329  32979185   100241                      
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div id="type-iii" class="section level4 unnumbered">
<h4>Type III<a class="anchor" aria-label="anchor" href="#type-iii"><i class="fas fa-link"></i></a>
</h4>
<div class="sourceCode" id="cb52"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/pkg/car/man/Anova.html">Anova</a></span><span class="op">(</span><span class="va">m</span>, type <span class="op">=</span> <span class="st">"3"</span><span class="op">)</span></code></pre></div>
<pre><code>## Anova Table (Type III tests)
## 
## Response: body_mass_g
##                 Sum Sq  Df  F value    Pr(&gt;F)    
## (Intercept) 1154266972   1 11514.96 &lt; 2.2e-16 ***
## species      143401584   2   715.29 &lt; 2.2e-16 ***
## sex           37090262   1   370.01 &lt; 2.2e-16 ***
## Residuals     32979185 329                       
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
<p><code><a href="https://rdrr.io/pkg/car/man/Anova.html">Anova()</a></code> is from the car package.</p>
<p>Overall effects of <strong>Species</strong> and <strong>Sex</strong></p>
<ul>
<li>Yes there are differences among <strong>Species</strong> (P &lt; 2.2e<sup>-16</sup>)</li>
<li>Yes there are differences between <strong>Sexes</strong> (P &lt; 2.2e<sup>-16</sup>)</li>
</ul>
<blockquote>
<p>Not a whole lot of information… <br>We’ll have to do some <strong><a href="linear-models.html#post-hoc-tests">Post-Hoc</a></strong> tests!</p>
</blockquote>
</div>
<div id="type-i-vs.-iii" class="section level4 unnumbered">
<h4>Type I vs. III<a class="anchor" aria-label="anchor" href="#type-i-vs.-iii"><i class="fas fa-link"></i></a>
</h4>
<p><strong>Why one or the other?</strong></p>
<div class="sourceCode" id="cb54"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">m1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">body_mass_g</span> <span class="op">~</span> <span class="va">species</span> <span class="op">+</span> <span class="va">sex</span>, data <span class="op">=</span> <span class="va">penguins</span><span class="op">)</span> <span class="co">#&lt;&lt;</span>
<span class="fu"><a href="https://rdrr.io/r/stats/anova.html">anova</a></span><span class="op">(</span><span class="va">m1</span><span class="op">)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Response: body_mass_g
##            Df    Sum Sq  Mean Sq F value    Pr(&gt;F)    
## species     2 145190219 72595110  724.21 &lt; 2.2e-16 ***
## sex         1  37090262 37090262  370.01 &lt; 2.2e-16 ***
## Residuals 329  32979185   100241                      
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
<div class="sourceCode" id="cb56"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">m2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">body_mass_g</span> <span class="op">~</span> <span class="va">sex</span> <span class="op">+</span> <span class="va">species</span>, data <span class="op">=</span> <span class="va">penguins</span><span class="op">)</span><span class="co">#&lt;&lt;</span>
<span class="fu"><a href="https://rdrr.io/r/stats/anova.html">anova</a></span><span class="op">(</span><span class="va">m2</span><span class="op">)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Response: body_mass_g
##            Df    Sum Sq  Mean Sq F value    Pr(&gt;F)    
## sex         1  38878897 38878897  387.86 &lt; 2.2e-16 ***
## species     2 143401584 71700792  715.29 &lt; 2.2e-16 ***
## Residuals 329  32979185   100241                      
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
<ul>
<li>For Type I ANOVAs, order matters with unbalanced samples
<ul>
<li>See that <code>Sum sq</code>, <code>Mean Sq</code> and <code>F value</code> all differ between the models</li>
</ul>
</li>
<li>Here, pretty minor, but important to remember with greater unbalances</li>
</ul>
<pre><code>## Anova Table (Type III tests)
## 
## Response: body_mass_g
##                 Sum Sq  Df  F value    Pr(&gt;F)    
## (Intercept) 1154266972   1 11514.96 &lt; 2.2e-16 ***
## species      143401584   2   715.29 &lt; 2.2e-16 ***
## sex           37090262   1   370.01 &lt; 2.2e-16 ***
## Residuals     32979185 329                       
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
<ul>
<li>Type III ANOVAs are not dependent on variable order</li>
</ul>
<blockquote>
<p>Type II ANOVAs do exist as well, but generally we use Type III in natural sciences</p>
</blockquote>
</div>
</div>
<div id="post-hoc-tests" class="section level3 unnumbered">
<h3>Post-Hoc tests<a class="anchor" aria-label="anchor" href="#post-hoc-tests"><i class="fas fa-link"></i></a>
</h3>
<p>When you would like to understand differences between 2+ levels in a categorical variable, you’ll need to do post-hoc tests.</p>
<p>Note:</p>
<ul>
<li>We do post-hoc tests <em>after</em> having found a <em>significant</em> of the variable in the ANOVA table.</li>
<li>There’s no point in doing post-hoc tests unless you have a variable with more than three levels, OR you’re interested in understanding the differences among categorical variables that also have an interaction</li>
<li>In our example, we don’t need to do post-hoc tests for sex, because there are only two levels, <code>male</code> and <code>female</code>. If there is a difference, then males are different than females, no question.</li>
</ul>
</div>
</div>
</div>

  <div class="chapter-nav">
<div class="prev"><a href="data-exploration.html"><span class="header-section-number">3</span> Data Exploration</a></div>
<div class="next"><a href="appendix-model-diagnostics.html">Appendix Model Diagnostics</a></div>
</div></main><div class="col-md-3 col-lg-2 d-none d-md-block sidebar sidebar-chapter">
    <nav id="toc" data-toggle="toc" aria-label="On this page"><h2>On this page</h2>
      <ul class="nav navbar-nav">
<li><a class="nav-link" href="#linear-models"><span class="header-section-number">4</span> Linear Models</a></li>
<li><a class="nav-link" href="#preamble"><span class="header-section-number">4.1</span> Preamble</a></li>
<li><a class="nav-link" href="#general-workflow"><span class="header-section-number">4.2</span> General Workflow</a></li>
<li>
<a class="nav-link" href="#simple-lms-in-r"><span class="header-section-number">4.3</span> (Simple) LMs in R</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#requirements">Requirements</a></li>
<li><a class="nav-link" href="#assumptions">Assumptions</a></li>
<li><a class="nav-link" href="#cautions">Cautions</a></li>
<li><a class="nav-link" href="#types-of-models">Types of models</a></li>
<li><a class="nav-link" href="#run-models-with-lm">Run models with lm()</a></li>
<li><a class="nav-link" href="#summary-tables-vs.-anova-tables">Summary tables vs. ANOVA tables</a></li>
</ul>
</li>
<li>
<a class="nav-link" href="#regressions"><span class="header-section-number">4.4</span> Regressions</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#create-model">Create Model</a></li>
<li><a class="nav-link" href="#model-diagnostics">Model Diagnostics</a></li>
<li><a class="nav-link" href="#summary-tables">Summary Tables</a></li>
<li><a class="nav-link" href="#interpreting-effects">Interpreting effects</a></li>
<li><a class="nav-link" href="#interpreting-the-effects-as-a-model">Interpreting the effects as a model</a></li>
<li><a class="nav-link" href="#extra">Extra</a></li>
</ul>
</li>
<li>
<a class="nav-link" href="#anovas"><span class="header-section-number">4.5</span> ANOVAs</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#create-model-1">Create Model</a></li>
<li><a class="nav-link" href="#model-diagnostics-1">Model Diagnostics</a></li>
<li><a class="nav-link" href="#summary-tables-1">Summary Tables</a></li>
<li><a class="nav-link" href="#interpreting-effects-1">Interpreting effects</a></li>
<li><a class="nav-link" href="#anova-tables">ANOVA Tables</a></li>
<li><a class="nav-link" href="#post-hoc-tests">Post-Hoc tests</a></li>
</ul>
</li>
</ul>

      <div class="book-extra">
        <ul class="list-unstyled">
          
        </ul>
</div>
    </nav>
</div>

</div>
</div> <!-- .container -->

<footer class="bg-primary text-light mt-5"><div class="container"><div class="row">

  <div class="col-12 col-md-6 mt-3">
    <p>"<strong>Steffi’s Practical Guide</strong>" was written by Steffi LaZerte. It was last built on 2021-10-01.</p>
  </div>

  <div class="col-12 col-md-6 mt-3">
    <p>This book was built by the <a class="text-light" href="https://bookdown.org">bookdown</a> R package.</p>
  </div>

</div></div>
</footer><!-- dynamically load mathjax for compatibility with self-contained --><script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script><script type="text/x-mathjax-config">const popovers = document.querySelectorAll('a.footnote-ref[data-toggle="popover"]');
for (let popover of popovers) {
  const div = document.createElement('div');
  div.setAttribute('style', 'position: absolute; top: 0, left:0; width:0, height:0, overflow: hidden; visibility: hidden;');
  div.innerHTML = popover.getAttribute('data-content');

  var has_math = div.querySelector("span.math");
  if (has_math) {
    document.body.appendChild(div);
    MathJax.Hub.Queue(["Typeset", MathJax.Hub, div]);
    MathJax.Hub.Queue(function() {
      popover.setAttribute('data-content', div.innerHTML);
      document.body.removeChild(div);
    })
  }
}
</script>
</body>
</html>
